(()=>{
const initData=window.Telegram?.WebApp?.initData||'';
const tgUser=window.Telegram?.WebApp?.initDataUnsafe?.user||null;
let profile=null,profilePhoto='',ready=false,timer=null;
const SEQUENTIAL_MIGRATION_KEY='academy-sequential-v1-ready';
const css=document.createElement('style');css.id='profile-clean-v1';css.textContent=`
.view:has(.profile-clean){padding:14px 14px 96px!important;display:block!important;overflow-y:auto!important;box-sizing:border-box!important}
.profile-clean{width:100%;max-width:620px;margin:0 auto;box-sizing:border-box}
.profile-clean-card{position:relative!important;width:100%!important;height:104px!important;min-height:104px!important;box-sizing:border-box!important;padding:14px 54px 14px 14px!important;display:flex!important;align-items:center!important;gap:14px!important;border-radius:22px!important;background:var(--surface)!important;border:1px solid var(--border)!important;box-shadow:0 10px 28px rgba(0,0,0,.16)!important;overflow:hidden!important}
.profile-clean-avatar{width:72px!important;height:72px!important;min-width:72px!important;border-radius:50%!important;overflow:hidden!important;border:2px solid var(--gold)!important;background:var(--surface-2)!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:0!important;box-shadow:none!important}
.profile-clean-avatar img{width:100%!important;height:100%!important;object-fit:cover!important;display:block!important}
.profile-clean-fallback{font-size:25px!important;font-weight:900!important;color:var(--text)!important}
.profile-clean-theme{position:absolute!important;right:12px!important;top:12px!important;width:38px!important;height:38px!important;padding:0!important;border:1px solid var(--border)!important;border-radius:12px!important;background:var(--surface-2)!important;color:var(--text)!important;display:flex!important;align-items:center!important;justify-content:center!important;box-shadow:none!important;z-index:5!important}
.profile-clean-theme svg{width:20px!important;height:20px!important;display:block!important}
.profile-clean-identity{min-width:0!important;display:flex!important;flex-direction:column!important;align-items:flex-start!important;justify-content:center!important;gap:2px!important}
.profile-clean-identity h2{margin:0!important;padding:0!important;font-size:20px!important;line-height:1.15!important;font-weight:900!important;color:var(--text)!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;max-width:calc(100vw - 150px)!important}
.profile-clean-username,.profile-clean-student{margin:0!important;padding:0!important;font-size:13px!important;line-height:1.25!important;color:var(--muted)!important}
.profile-clean-settings-title{margin:18px 4px 8px!important;font-size:14px!important;line-height:1.2!important;font-weight:800!important;color:var(--muted)!important}
.profile-clean-settings{width:100%!important;box-sizing:border-box!important;border-radius:20px!important;background:var(--surface)!important;border:1px solid var(--border)!important;overflow:hidden!important;box-shadow:0 10px 28px rgba(0,0,0,.12)!important}
.profile-clean-row{height:78px!important;min-height:78px!important;box-sizing:border-box!important;padding:12px 14px!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:12px!important;background:transparent!important;border:0!important}
.profile-clean-row+ .profile-clean-row{border-top:1px solid var(--border)!important}
.profile-clean-label{min-width:0!important;display:flex!important;flex-direction:column!important;gap:3px!important}
.profile-clean-label strong{font-size:15px!important;line-height:1.1!important;color:var(--text)!important}
.profile-clean-label span{font-size:12px!important;line-height:1.2!important;color:var(--muted)!important}
.profile-clean-controls{display:flex!important;align-items:center!important;gap:6px!important;flex-shrink:0!important}
.profile-clean-controls button{height:38px!important;min-width:42px!important;padding:0 9px!important;border-radius:11px!important;border:1px solid var(--border)!important;background:var(--surface-2)!important;color:var(--text)!important;font-weight:800!important;box-shadow:none!important}
.profile-clean-controls .selected{border-color:var(--gold)!important;background:var(--surface-2)!important}
@media(max-width:430px){.view:has(.profile-clean){padding:10px 10px 92px!important}.profile-clean-card{height:92px!important;min-height:92px!important;padding:10px 48px 10px 10px!important;gap:11px!important;border-radius:18px!important}.profile-clean-avatar{width:62px!important;height:62px!important;min-width:62px!important}.profile-clean-theme{right:9px!important;top:9px!important;width:34px!important;height:34px!important;border-radius:10px!important}.profile-clean-theme svg{width:18px!important;height:18px!important}.profile-clean-identity h2{font-size:17px!important;max-width:calc(100vw - 130px)!important}.profile-clean-username,.profile-clean-student{font-size:11px!important}.profile-clean-settings-title{margin-top:14px!important}.profile-clean-row{height:72px!important;min-height:72px!important;padding:10px!important}.profile-clean-label strong{font-size:14px!important}.profile-clean-label span{font-size:11px!important}.profile-clean-controls button{height:34px!important;min-width:38px!important;padding:0 7px!important}}
`;
document.head.appendChild(css);
async function api(path,body){const r=await fetch(`${API}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`Profile API ${r.status}`);return r.json()}
function setPhotoBlob(blob){if(!blob||!blob.size)return false;if(profilePhoto.startsWith('blob:'))URL.revokeObjectURL(profilePhoto);profilePhoto=URL.createObjectURL(blob);if(state.route==='profile')render();return true}
async function loadCustomAvatar(){if(!initData)return false;try{const r=await fetch(`${API}/profile/avatar/get`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({init_data:initData})});if(!r.ok)return false;return setPhotoBlob(await r.blob())}catch(e){console.warn('Custom avatar:',e);return false}}
async function loadTelegramPhoto(){if(!initData)return;try{const r=await fetch(`${API}/profile/photo`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({init_data:initData})});if(!r.ok)return;setPhotoBlob(await r.blob())}catch(e){console.warn('Profile photo:',e)}}
function imageToDataUrl(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{try{const size=Math.min(img.naturalWidth,img.naturalHeight),sx=Math.max(0,(img.naturalWidth-size)/2),sy=Math.max(0,(img.naturalHeight-size)/2),canvas=document.createElement('canvas');canvas.width=512;canvas.height=512;canvas.getContext('2d').drawImage(img,sx,sy,size,size,0,0,512,512);URL.revokeObjectURL(url);resolve(canvas.toDataURL('image/jpeg',.86))}catch(e){URL.revokeObjectURL(url);reject(e)}};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('image'))};img.src=url})}
async function uploadAvatar(file){if(!file||!initData)return;try{await api('/profile/avatar',{init_data:initData,image:await imageToDataUrl(file)});await loadCustomAvatar();haptic()}catch(e){console.warn('Avatar upload:',e)}}
function localPayload(){return{init_data:initData,completed:state.completed,favorites:state.favorites,language:state.language,theme:state.theme,font_scale:state.fontScale}}
async function push(){if(!initData||!ready)return;try{await api('/profile/save',localPayload())}catch(e){console.warn('Profile sync:',e)}}
function schedulePush(){clearTimeout(timer);timer=setTimeout(push,250)}
const localSave=save;save=function(){localSave();schedulePush()};
const cleanRenderProfile=()=>{
const user=profile||tgUser||{},name=[user.first_name,user.last_name].filter(Boolean).join(' ')||'Telegram',username=user.username?`@${user.username}`:'',photo=profilePhoto||user.photo_url||'',initials=(user.first_name||'ӀА').slice(0,2),dark=state.theme==='dark',themeLabel=dark?t('enableLight'):t('enableDark');
const themeIcon=dark?'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4" fill="currentColor"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg>':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.2 15.4A8.6 8.6 0 0 1 8.6 3.8 8.7 8.7 0 1 0 20.2 15.4Z" fill="currentColor"/></svg>';
const avatar=photo?`<img src="${escapeHtml(photo)}" alt="" loading="eager">`:`<span class="profile-clean-fallback">${escapeHtml(initials)}</span>`;
view.innerHTML=`<div class="profile-clean"><section class="profile-clean-card"><button type="button" class="profile-clean-theme" data-theme-profile aria-label="${escapeHtml(themeLabel)}" title="${escapeHtml(themeLabel)}">${themeIcon}</button><button type="button" class="profile-clean-avatar" data-avatar-picker aria-label="${escapeHtml(t('profile'))}">${avatar}</button><input data-avatar-input type="file" accept="image/jpeg,image/png,image/webp" hidden><div class="profile-clean-identity"><h2>${escapeHtml(name)}</h2>${username?`<p class="profile-clean-username">${escapeHtml(username)}</p>`:''}<p class="profile-clean-student">${t('academyStudent')}</p></div></section><div class="profile-clean-settings-title">${escapeHtml(t('changeDesign'))}</div><section class="profile-clean-settings"><div class="profile-clean-row"><div class="profile-clean-label"><strong>Aa</strong><span>${escapeHtml(t('about'))}</span></div><div class="profile-clean-controls"><button type="button" data-font="minus">A−</button><button type="button" data-font="reset">${Math.round(state.fontScale*100)}%</button><button type="button" data-font="plus">A+</button></div></div><div class="profile-clean-row"><div class="profile-clean-label"><strong>${escapeHtml(t('interfaceLanguage'))}</strong><span>${escapeHtml(t('now'))}: ${state.language==='ru'?escapeHtml(t('russian')):escapeHtml(t('chechen'))}</span></div><div class="profile-clean-controls"><button type="button" class="${state.language==='ru'?'selected':''}" data-language="ru">${escapeHtml(t('russian'))}</button><button type="button" class="${state.language==='ce'?'selected':''}" data-language="ce">${escapeHtml(t('chechen'))}</button></div></div></section></div>`;
const picker=view.querySelector('[data-avatar-picker]'),input=view.querySelector('[data-avatar-input]');picker?.addEventListener('click',()=>input?.click());input?.addEventListener('change',()=>uploadAvatar(input.files?.[0]));
};
renderProfile=cleanRenderProfile;
async function start(){if(!initData)return;try{const data=await api('/profile/load',{init_data:initData});profile=data.profile;if(data.is_new){state.theme='dark';state.fontScale=.9;state.completed=[];document.documentElement.dataset.theme='dark';localStorage.setItem(SEQUENTIAL_MIGRATION_KEY,'1');localSave();ready=true;await push()}else{state.completed=Array.isArray(profile.completed)?profile.completed:[];state.favorites=Array.isArray(profile.favorites)?profile.favorites:[];state.language=profile.language==='ru'?'ru':'ce';state.theme=profile.theme==='light'?'light':'dark';state.fontScale=Number(profile.font_scale)||.9;document.documentElement.dataset.theme=state.theme;const reset=!localStorage.getItem(SEQUENTIAL_MIGRATION_KEY);if(reset){state.completed=[];localStorage.setItem(SEQUENTIAL_MIGRATION_KEY,'1')}localSave();ready=true;if(reset)await push()}render();if(!(await loadCustomAvatar()))await loadTelegramPhoto()}catch(e){console.warn('Profile load:',e)}}
start();
})();
