(()=>{
const svg={home:'<svg viewBox="0 0 24 24"><path d="m3 10 9-7 9 7M5 9.5V21h14V9.5M9 21v-7h6v7"/></svg>',courses:'<svg viewBox="0 0 24 24"><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v16H6.5A2.5 2.5 0 0 1 4 21.5zM4 5.5v16M8 7h8M8 11h8"/></svg>',profile:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4.5 21a7.5 7.5 0 0 1 15 0"/></svg>',channel:'<svg viewBox="0 0 24 24"><path d="m21 4-3 17-6-5-1-6-5-2zM8 13l8-6"/></svg>',faq:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M9.5 9a2.6 2.6 0 1 1 4.5 1.8c-1.2 1.1-2 1.5-2 3M12 17h.01"/></svg>',share:'<svg viewBox="0 0 24 24"><circle cx="18" cy="5" r="2.5"/><circle cx="6" cy="12" r="2.5"/><circle cx="18" cy="19" r="2.5"/><path d="m8.2 10.8 7.5-4.4M8.2 13.2l7.5 4.4"/></svg>',theme:'<svg viewBox="0 0 24 24"><path d="M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6 7 7M17 17l1.4 1.4M18.4 5.6 17 7M7 17l-1.4 1.4"/><circle cx="12" cy="12" r="4"/></svg>',language:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a14 14 0 0 1 0 18M12 3a14 14 0 0 0 0 18"/></svg>',info:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 10v6M12 7h.01"/></svg>',admin:'<svg viewBox="0 0 24 24"><path d="M4 5h16v11H8l-4 4z"/><circle cx="9" cy="10" r="1"/><circle cx="12" cy="10" r="1"/><circle cx="15" cy="10" r="1"/></svg>'};
const CHANNEL_URL='https://t.me/Akidatan_Akademi_1',ADMIN_BOT_URL='https://t.me/AkidatanAcademyAppBot?start=contact_admin',SHARE_URL='https://mehmedjanbeno-web.github.io/Akidatan-Academy/',trigger=document.getElementById('side-menu-toggle');if(!trigger)return;
const ru={brand:'Ӏакъидатан Академия',brandSub:'Учебное пространство',sectionLearning:'Обучение',home:'Главная',courses:'Курсы',favorites:'Избранное',sectionAcademy:'АКАДЕМИЯ',channel:'Канал Академии',channelSub:'Новости, уроки и материалы',faq:'Вопросы и ответы',faqSub:'Частые вопросы об обучении',share:'Поделиться приложением',admin:'Связь с админом',adminSub:'Написать сообщение через бота',sectionApp:'ПРИЛОЖЕНИЕ',profile:'Мой профиль',appearance:'Оформление',language:'Язык интерфейса',about:'Об Академии',footer:'Официальный канал и поддержка доступны через Telegram',faqTitle:'Вопросы и ответы',faq1q:'Как начать обучение?',faq1a:'Откройте «Курсы», выберите курс и начните с первого урока.',faq2q:'Как сохранить урок?',faq2a:'Откройте урок и добавьте его в «Избранное».',faq3q:'Как отметить урок пройденным?',faq3a:'Внутри урока используйте кнопку отметки о прохождении.',faq4q:'Как изменить язык и размер текста?',faq4a:'Откройте «Мой профиль» — там находятся настройки языка и оформления.',faq5q:'Где выходят новые материалы?',faq5a:'Новые материалы и объявления публикуются в официальном Telegram-канале Академии.',aboutTitle:'Об Академии',aboutText:'Это приложение создано для того, чтобы облегчить вам изучение и прослушивание уроков „Академии Акиды“. Главная площадка этого проекта указана выше. Если кто-то не знает, как перенять все эти знания, или сталкивается с непониманием — вы можете на этой главной площадке во всём разобраться (догнать программу). Нажав сверху на „Канал Академии“, вы сможете задать там любые возникшие вопросы...',aboutVersion:'Версия приложения: 2026'};
const ce={brand:'Ӏакъидатан Академия',brandSub:'Дешаран майда',sectionLearning:'Дешар',home:'Коьрта агIо',courses:'Курсаш',favorites:'Хаьржинарш',sectionAcademy:'АКАДЕМИ',channel:'Академин канал',channelSub:'Керла хьаьркаш, урокаш а, материалаш а',faq:'Хаттарш а, жоьпаш а',faqSub:'Дешарх лаьцна кест-кеста луш долу хаттарш',share:'Приложенех лаьцна дӀахьедан',admin:'Админца зӀе',adminSub:'Ботехь сообщение язде',sectionApp:'ПРИЛОЖЕНИ',profile:'Сан профиль',appearance:'Куц',language:'Интерфейсан мотт',about:'Академин хьокъехь',footer:'Официальни канал а, гӀо а Telegram тӀехь ду',faqTitle:'Хаттарш а, жоьпаш а',faq1q:'Муха дешар дӀадахьа деза?',faq1a:'«Курсаш» чу гIо, курс харжа, тIаккха хьалхарчу урокаца дӀадоладе.',faq2q:'Муха урок Iалашъян еза?',faq2a:'Урок схьаэлла а, «Хаьржинарш» тӀе тӀетоха.',faq3q:'Муха билгалъян еза урок чекхъяккхина аьлла?',faq3a:'Урок чухула чекхъялар билгалден кнопка лелае.',faq4q:'Муха мотт а, текстийн барам а хийца беза?',faq4a:'«Сан профиль» чу гIо — цигахь интерфейсан мотт а, оформлени а хийца йиш ю.',faq5q:'Мичахь гучудовлу керла материалаш?',faq5a:'Керла материалаш а, кхайкхамаш а Академин официальни Telegram-каналехь арахоьцу.',aboutTitle:'Академин хьокъехь',aboutText:'ХӀара „Ӏакъидатан академи“ урокаш Ӏамо а, ладогӀа а вайна атта хилийта йина гӀирс (приложение) бу. Кху гӀирсан коьрта майда лакхахь йазйина йу. Кху чохь ша-дерриг Ӏилма схьаэца ца хууш йа цхьа хӀума ца кхеташ волчунна — кху коьрта майданахь тӀаьхьакхиа (хатта) йиш йу шун. Лакхахь „Академин канал“ аьллачунна тӀе таӀийча, цигахь шун йиш хир йу цакхетарг хатта. Ткъа кху гӀирсан гӀалаташ йа цакхетамаш вайга хаийта йиш йу, лакхахь „Админца зӀе“ аьллачунна тӀе таӀийча. АллахӀа Ӏилманехь совдохийла вай! АллахӀа Ӏилма Ӏамор атта дойла, марздойла!',aboutVersion:'Приложенин верси: 2026'};
function currentLanguage(){return (window.state?.language||localStorage.getItem('academy-language')||document.documentElement.lang||'ru')==='ce'?'ce':'ru'}
function labels(){return currentLanguage()==='ce'?ce:ru}
const backdrop=document.createElement('div');backdrop.className='side-menu-backdrop';document.body.appendChild(backdrop);
function item(a,i,l,s=''){return `<button class="side-menu-item" type="button" data-side-action="${a}"><span class="side-menu-icon">${i}</span><span class="side-menu-copy"><b>${l}</b>${s?`<small>${s}</small>`:''}</span><span class="side-menu-arrow">›</span></button>`}
function faq(q,a){return `<details class="side-menu-faq-item"><summary>${q}<span>+</span></summary><p>${a}</p></details>`}
function renderMenu(){const l=labels();backdrop.innerHTML=`<aside class="side-menu" role="dialog" aria-modal="true"><button class="side-menu-close" type="button" data-side-close>×</button><div class="side-menu-brand"><div class="side-menu-brand-mark">ӀА</div><div><strong>${l.brand}</strong><span>${l.brandSub}</span></div></div><div class="side-menu-section-title">${l.sectionLearning}</div><div class="side-menu-list">${item('home',svg.home,l.home)}</div><div class="side-menu-section-title">${l.sectionAcademy}</div><div class="side-menu-list">${item('channel',svg.channel,l.channel,l.channelSub)}${item('faq',svg.faq,l.faq,l.faqSub)}${item('share',svg.share,l.share)}${item('admin',svg.admin,l.admin,l.adminSub)}</div><div class="side-menu-faq" data-side-faq aria-hidden="true"><button type="button" class="side-menu-faq-close" data-faq-close>×</button><div class="side-menu-faq-title">${l.faqTitle}</div><div class="side-menu-faq-list">${faq(l.faq1q,l.faq1a)}${faq(l.faq2q,l.faq2a)}${faq(l.faq3q,l.faq3a)}${faq(l.faq4q,l.faq4a)}${faq(l.faq5q,l.faq5a)}</div></div><div class="side-menu-section-title">${l.sectionApp}</div><div class="side-menu-list">${item('appearance',svg.theme,l.appearance)}${item('language',svg.language,l.language)}${item('about',svg.info,l.about)}</div><div class="side-menu-about" data-side-about aria-hidden="true"><strong>${l.aboutTitle}</strong><p>${l.aboutText}</p><p>${l.aboutVersion}</p></div><div class="side-menu-footer">${l.footer}</div></aside>`}
renderMenu();
const shareSheet=document.createElement('div');shareSheet.className='academy-share-sheet';document.body.appendChild(shareSheet);
function hideShare(){shareSheet.classList.remove('open')}
function showShare(){const publicUrl='https://t.me/AkidatanAcademyAppBot?start=app',isCe=currentLanguage()==='ce',title=isCe?'Приложени дӀахьедан':'Поделиться приложением',desc=isCe?'Ӏакъидатан Академия — дешарна лерина приложение':'Ӏакъидатан Академия — приложение для обучения',copy=isCe?'🔗 Ссылка копировать ян':'🔗 Копировать ссылку',closeText=isCe?'ДӀакъовла':'Закрыть';shareSheet.innerHTML=`<div class="academy-share-card"><h2>📤 ${title}</h2><p>${desc}</p><div class="academy-share-row"><button data-share-tg>✈️ Telegram</button></div><button class="academy-share-copy" data-share-copy>${copy}</button><button class="academy-share-close" data-share-close>${closeText}</button></div>`;shareSheet.classList.add('open');shareSheet.onclick=e=>{if(e.target===shareSheet||e.target.closest('[data-share-close]'))return hideShare();const msg=`${desc}\n${publicUrl}`;if(e.target.closest('[data-share-tg]'))return telegram(`https://t.me/share/url?url=${encodeURIComponent(publicUrl)}&text=${encodeURIComponent(desc)}`);if(e.target.closest('[data-share-copy]'))navigator.clipboard?.writeText(publicUrl).then(()=>{e.target.closest('[data-share-copy]').textContent=isCe?'✅ Ссылка копировать йина':'✅ Ссылка скопирована'}).catch(()=>{})}}
function close(){backdrop.classList.remove('open');document.body.classList.remove('side-menu-open');trigger.setAttribute('aria-expanded','false')}
function go(r){close();navigate(r)}
function telegram(u){const t=window.Telegram?.WebApp;try{if(t?.openTelegramLink){t.openTelegramLink(u);setTimeout(function(){t.close()},300);return true}}catch(_){}window.location.href=u;return true}
function open(){renderMenu();backdrop.classList.add('open');document.body.classList.add('side-menu-open');trigger.setAttribute('aria-expanded','true')}
trigger.addEventListener('click',open);
backdrop.addEventListener('click',e=>{if(e.target===backdrop||e.target.closest('[data-side-close]')){e.preventDefault();e.stopPropagation();close();return}if(e.target.closest('[data-faq-close]')){e.preventDefault();e.stopPropagation();backdrop.querySelector('[data-side-faq]')?.classList.remove('open');backdrop.querySelector('[data-side-faq]')?.setAttribute('aria-hidden','true');return}const target=e.target.closest('[data-side-action]');if(!target)return;e.preventDefault();e.stopPropagation();const a=target.dataset.sideAction;if(a==='home')return go('home');if(a==='courses')return go('courses');if(a==='profile')return go('profile');if(a==='favorites')return go('favorites');if(a==='appearance'||a==='language')return go('profile');if(a==='channel')return telegram(CHANNEL_URL);if(a==='share'){close();showShare();return}if(a==='admin')return telegram(ADMIN_BOT_URL);if(a==='faq'){const x=backdrop.querySelector('[data-side-faq]');x?.classList.add('open');x?.setAttribute('aria-hidden','false');return}if(a==='about'){const x=backdrop.querySelector('[data-side-about]');x?.classList.toggle('open');x?.setAttribute('aria-hidden',x?.classList.contains('open')?'false':'true');return}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&backdrop.classList.contains('open'))close()});
})();
